In [1]:
# import libraries
import pandas as pd
import numpy as np

In [2]:
# load the raw data
df=pd.read_excel("Power BI - Final Project.xlsx")
df.head(3)

,Unique ID,Email,Date Taken (America/New_York),Time Taken (America/New_York),Browser,OS,City,Country,Referrer,Time Spent,...,Q6 - How Happy are you in your Current Position with the following? (Management),Q6 - How Happy are you in your Current Position with the following? (Upward Mobility),Q6 - How Happy are you in your Current Position with the following? (Learning New Things),Q7 - How difficult was it for you to break into Data?,"Q8 - If you were to look for a new job today, what would be the most important thing to you?",Q9 - Male/Female?,Q10 - Current Age,Q11 - Which Country do you live in?,Q12 - Highest Level of Education,Q13 - Ethnicity
0,62a33b3db4da29969c62df3d,anonymous,6/10/2022,8:38,NaN,NaN,NaN,NaN,NaN,0:00:44,...,5.0,5.0,7.0,Very Difficult,Remote Work,Male,26,United States,NaN,White or Caucasian
1,62a33ba1bae91e4b8b82e35c,anonymous,6/10/2022,8:40,NaN,NaN,NaN,NaN,NaN,0:01:30,...,2.0,1.0,3.0,Very Difficult,Remote Work,Male,36,Canada,NaN,Asian or Asian American
2,62a33c2cbc6861bf3176bec1,anonymous,6/10/2022,8:42,NaN,NaN,NaN,NaN,NaN,0:02:18,...,5.0,7.0,7.0,Easy,Good Work/Life Balance,Male,23,Other (Please Specify):Nigeria,NaN,Black or African American

# Background Overall Breakdown

The data was taken from the "Alex the Analyst Full Power BI Guided Project | Microsoft Power BI for Beginners" tutorial dataset. Further data cleaning will be processed in this notebook. Before diving into the cleaning, the key features of the dataset will be presented.

## Key Features

1. **Voter's Role**
    - Question: Which Title Best Fits Your Current Role?

2. **Career Transfer**
    - Question: Did You Switch Careers into Data?

3. **Current Yearly Salary (in USD)**
    - Question: Current Yearly Salary

4. **Industry**
    - Question: What Industry Do You Work In?

5. **Favorite Programming Language**
    - Question: Favorite Programming Language

6. **Job Satisfaction**
    - Question: How Happy Are You in Your Current Position with the Following?
        - Salary
        - Work/Life Balance
        - Coworkers
        - Management
        - Upward Mobility
        - Learning New Things

7. **Difficulty Breaking into Data**
    - Question: How Difficult Was It for You to Break Into Data?

8. **Job Preferences**
    - Question: If You Were to Look for a New Job Today, What Would Be the Most Important Thing to You?
        - Voter's Prefer Work Conditions

9. **Gender**
    - Question: Gender?

10. **Age**
    - Question: Current Age

11. **Voter's Country**
    - Question: Which Country Do You Live In?

12. **Highest Level of Education**
    - Question: Highest Level of Education

13. **Ethnicity**
    - Question: Ethnicity

## Data Cleaning Process

- [ ] Step 1: check duplicates, missing data, faulty data
- [ ] Step 2: drop unnecessary columns
- [ ] Step 3: preparing the data for further analysis(creating range, category column, natural language processing etc...)

(Add more steps as needed)

## STEP 1: check duplicates, missing data, faulty data

In [3]:
## duplicate
df.duplicated().any()

False

* No duplicates

In [4]:
## missing values
df.isnull().sum()

Unique ID                                                                                         0
Email                                                                                             0
Date Taken (America/New_York)                                                                     0
Time Taken (America/New_York)                                                                     0
Browser                                                                                         630
OS                                                                                              630
City                                                                                            630
Country                                                                                         630
Referrer                                                                                        630
Time Spent                                                                                        0
Q1 - Which Title Best Fits your Current Role?                                                     0
Q2 - Did you switch careers into Data?                                                            0
Q3 - Current Yearly Salary (in USD)                                                               0
Q4 - What Industry do you work in?                                                                0
Q5 - Favorite Programming Language                                                                0
Q6 - How Happy are you in your Current Position with the following? (Salary)                      7
Q6 - How Happy are you in your Current Position with the following? (Work/Life Balance)          10
Q6 - How Happy are you in your Current Position with the following? (Coworkers)                  11
Q6 - How Happy are you in your Current Position with the following? (Management)                 12
Q6 - How Happy are you in your Current Position with the following? (Upward Mobility)            13
Q6 - How Happy are you in your Current Position with the following? (Learning New Things)         5
Q7 - How difficult was it for you to break into Data?                                             0
Q8 - If you were to look for a new job today, what would be the most important thing to you?      0
Q9 - Male/Female?                                                                                 0
Q10 - Current Age                                                                                 0
Q11 - Which Country do you live in?                                                               0
Q12 - Highest Level of Education                                                                 52
Q13 - Ethnicity                                                                                   0
dtype: int64

* Some columns (Browser, City, Os, City, Country, Referrer ) are completely empty. They will be droped in the next step
* Some parameters of Q6 are missing and they can be filled with the average or mode value of the entire column
* Missing values in Education column can be filled "Unknown"

In [5]:
## filling null values in Q6 parameters with the mode (most common values)
parameters_Q6=["Salary","Work/Life Balance","Coworkers","Management","Upward Mobility","Learning New Things"]
for parameter in parameters_Q6:
    column=f"Q6 - How Happy are you in your Current Position with the following? ({parameter})"
    mode=df[column].mode().iloc[0]
    df[column].fillna(value=mode,inplace=True)

In [6]:
## filling null values in highest level of Education column  with "Unknown"
df["Q12 - Highest Level of Education"].fillna("Unknown",inplace=True)

## STEP 2: dropping unnecessary columns

In [7]:
unused_columns=["Email","Date Taken (America/New_York)","Time Taken (America/New_York)","Browser",
               "OS","City","Country","Referrer","Time Spent"]

df.drop(columns=unused_columns,inplace=True)

In [8]:
## changing the columns names for further EDA
new_columns_names={"Q1 - Which Title Best Fits your Current Role?":"Current_Role",
                  "Q2 - Did you switch careers into Data?":"Switched_Career",
                    "Q3 - Current Yearly Salary (in USD)":"Current_salary_Range",
                    "Q4 - What Industry do you work in?":"Working_Industry",
                    "Q5 - Favorite Programming Language":"Favorite_Programming_Language",
                    "Q6 - How Happy are you in your Current Position with the following? (Salary)":"Happiness_in_Pos(Salary)",
                    "Q6 - How Happy are you in your Current Position with the following? (Work/Life Balance)":"Happiness_in_Pos(Work/Life Balance)",
                    "Q6 - How Happy are you in your Current Position with the following? (Coworkers)":"Happiness_in_Pos(Coworkers)",
                    "Q6 - How Happy are you in your Current Position with the following? (Management)":"Happiness_in_Pos(Management)",
                    "Q6 - How Happy are you in your Current Position with the following? (Upward Mobility)":"Happiness_in_Pos(Upward Mobility)",
                    "Q6 - How Happy are you in your Current Position with the following? (Learning New Things)":"Happiness_in_Pos(Learning New Things)",
                    "Q7 - How difficult was it for you to break into Data?":"difficulties_Break_into_Data",
                    "Q8 - If you were to look for a new job today, what would be the most important thing to you?":"Prefered_Working_Condition",
                    "Q9 - Male/Female?":"Gender",
                    "Q10 - Current Age":"Current_Age",
                    "Q11 - Which Country do you live in?":"Current_Country",
                    "Q12 - Highest Level of Education":"Highest_Education",
                    "Q13 - Ethnicity":"Ethnicity"
                    }
df.rename(columns=new_columns_names,inplace=True)

## Step 3: preparing the data for further analysis(creating range, category column, natural language

In [9]:
df_copy=df.copy()

In [10]:
## function to expand "Other (Please Specify)"
def expand(column):
    mask = df_copy[column].str.startswith('Other (Please Specify):')
    df_copy.loc[mask, column] = df_copy.loc[mask, column].str.split(':').str[1].str.strip()

In [11]:
## For current_role column
## Expand Others 
expand("Current_Role")

## <span style="color:green">Current_Role</span>

## I can categorize the column into the new Role_category 
### Data Analysis/Reporting:
- Data Analyst
- FP&A Analyst
- Analyst
- Reporting Admin
- Billing Analyst
- Marketing Data Specialist
- Finance Analyst
- Data Coordinator
- Predictive Analyst
- Investigation Specialist
- Power BI Developer

### Business Intelligence:
- BI Developer
- Manager, Business Intelligence Development
- Business Intelligence Consultant
- Director of Data Analytics
- Business Intelligence Engineer
- Business Intelligence Developer
- Business Intelligence Analyst
- BI Consultant
- BI Manager

### Data Science/Analytics:
- Data Scientist
- Analytics Consultant
- Insights Analyst
- Analytics Manager
- Analytics Engineer
- Analyst Primary Market Intelligence
- Jr. Data Scientist
- Senior Business Analyst
- GIS Analyst
- Data Scientist Intern
- Predictive Analyst

### Database Management:
- Data Engineer
- Data Architect
- Database Developer
- Database Manager
- DBA (Database Administrator)
- Data Steward

### Software Development/Engineering:
- Software Engineer
- Software Developer
- Tableau Admin
- Other (Please Specify)
- Continuous Quality Improvement Specialist
- Junior Software Engineer
- Software Engineer, AI
- Systems Configuration
- Support Engineer

### Education and Training:
- Student/Looking/None
- Educator
- Teacher
- Student working as a data analyst intern

### Management and Leadership:
- Manager
- Manager of a Team of Data Analysts
- Director
- BI Manager
- Data Manager

### Consulting and Specialized Roles:
- Analytics Manager
- Learning Management Specialist
- Research Analyst
- Research Associate
- Business Analyst
- Business Analys
- Consultant
- Informatics Specialist
- Technical Consultant
- SAP Security Analyst
- Web Developer
- Product Owner
- Presales Engineer

### Other/Not Specified Roles:
- Does a social media analyst count?
- I wo

In [12]:

# Define function to categorize roles
def categorize_role(role):
    if 'Data Analyst' in role:
        return 'Data Analysis/Reporting'
    elif 'Business Intelligence' in role or 'BI' in role:
        return 'Business Intelligence'
    elif 'Data Science' in role or 'Analytics' in role:
        return 'Data Science/Analytics'
    elif 'Database' in role or 'DBA' in role:
        return 'Database Management'
    elif 'Software' in role or 'Developer' in role or 'Engineer' in role:
        return 'Software Development/Engineering'
    elif 'Education' in role or 'Student' in role or 'Teacher' in role:
        return 'Education and Training'
    elif 'Management' in role or 'Director' in role or 'Manager' in role:
        return 'Management and Leadership'
    elif 'Consultant' in role or 'Specialist' in role:
        return 'Consulting and Specialized Roles'
    else:
        return 'Other/Not Specified Roles'

In [13]:
# Apply categorization function to the 'Role' column
df_copy['Role_Category'] = df_copy['Current_Role'].apply(categorize_role)

In [14]:
df_copy["Role_Category"].value_counts()

Data Analysis/Reporting             382
Education and Training               92
Other/Not Specified Roles            77
Software Development/Engineering     47
Data Science/Analytics                8
Business Intelligence                 8
Database Management                   7
Management and Leadership             5
Consulting and Specialized Roles      4
Name: Role_Category, dtype: int64

## <span style="color:green">Current_salary_Range</span>
### I can create two new upper bound and lower bound columns

In [15]:
## For current_salary_range
## create lower bond(salary) and upper bond(salary) columns
# Function to calculate midpoint
def calculate_midpoint(salary_range):
    salary_range = salary_range.replace('k', '').replace('+', '').replace('-', '+').split('+')
    lower_bound = float(salary_range[0])
    upper_bound = float(salary_range[1]) if len(salary_range) > 1 else lower_bound
    return lower_bound, upper_bound

In [16]:
# Apply the function to create separate columns for lower and upper bounds
df_copy[['Lower_Bound(Salary)', 'Upper_Bound(Salary)']] = df_copy['Current_salary_Range'].apply(lambda x: pd.Series(calculate_midpoint(x)))

In [17]:
## For Working_Industry column
## Expand Others 
expand("Working_Industry")

## <span style="color:green">Working_Industry</span>

## I can categorize the column into the new Industry_category 
### Healthcare:
- Healthcare

### Finance:
- Finance
- Insurance
- Audit Firm

### Clean Energy:
- Clean Energy
- Renewable Resources

### Coworking Space:
- Coworking Space

### Retail:
- Retail
- Food & Beverage
- Foodservice
- Consumer retail
- Retails
- Digital Marketing
- Direct Marketing
- FMCG (Fast-Moving Consumer Goods)

### Telecommunication:
- Telecommunication

### Logistics:
- Logistics
- Third Party Logistics
- Supply Chain - warehousing, transportation, and distribution
- Supply Chain
- last mile delivery logistics
- Logistics and warehousing
- Public transport
- Air transport
- Transportation

### Igaming:
- Igaming

### Tech:
- Tech
- IT
- Electronics
- Digital Mar
- Data insights company
- Digital Marketing

### Education:
- Education
- Currently studying . Previously worked in Power Generation
- Not working at the moment, but previously I have been in the Education industry
- Market research
- Culinary
- Demography and Social Statistics
- i`m currently a student
- Student
- I am a student
- I am student.
- Unemployed, trying to switch career
- Taking bootcamp
- Interning in Sciences, Weather and Meteorological data

### Construction:
- Construction
- Manufacturing (Chemicals)
- Manufa
- Manufacturing
- Manufacturering
- Automobile Industry
- Automobile (cars)
- General contractor

### Aviation:
- Aviation
- Aerospace
- Avia
- Space & Defense

### Other (Please Specify):
- Other (Please Specify)

### Utilities:
- Utilities

### Not working yet:
- Not working yet
- None
- None for now

### Manuf:
- Manuf
- Fashion/online store
- sports
- Agriculture
- Management
- Warehouse
- NGO - Legislation
- Cobsukting
- Workforce

### Consulting:
- Consulting
- Consulti
- Cons
- Consultation
- Outsourcing
- Consulting
- Consulting

### Government:
- Government
- State Government
- Culture
- Government programs
- Government
- State
- Gover
- Government Administration
- Defense

### Entertainment:
- Entertainment
- sports
- Social work
- Hospitality
- Hospitality
- sports

### Marketing:
- Marketing
- Advertising
- Marketing
- Market research
- Digital Marketing
- Direct Marketing

### Biotech:
- Biotech

### Semiconductor manufacturing:
- Semiconductor manufacturing

### Customer Service:
- Customer Service
- Customer service

### Ecom:
- Ecom
- E-commerce
- Ecommerce

### Law Enforcement:
- Law Enforcement
- Police / Emergency Services

### Others/Not Specified:
- Not currently working
- Home maker
- Maritime
- Urbanism
- Looking for a job
- Sensors
- Professional Services
- Home and living
- Non Profit Organization
- Homelessness

In [18]:

# Define function to categorize industries
def categorize_industry(industry):
    if 'Healthcare' in industry:
        return 'Healthcare'
    elif 'Finance' in industry or 'Audit Firm' in industry or 'Legal' in industry:
        return 'Finance'
    elif 'Clean Energy' in industry or 'Renewable Resources' in industry or 'Energy' in industry or 'Oil and gas' in industry:
        return 'Clean Energy'
    elif 'Coworking Space' in industry:
        return 'Coworking Space'
    elif 'Retail' in industry or 'Food & Beverage' in industry or 'Consumer retail' in industry or 'Digital Marketing' in industry:
        return 'Retail'
    elif 'Telecommunication' in industry:
        return 'Telecommunication'
    elif 'Logistics' in industry or 'Third Party Logistics' in industry or 'Supply Chain - warehousing, transpiration and' in industry or 'Distribution' in industry or 'Public transport' in industry or 'Air transport' in industry or 'Transportation' in industry or 'last mile delivery logistics' in industry:
        return 'Logistics'
    elif 'Igaming' in industry:
        return 'Igaming'
    elif 'Tech' in industry or 'IT' in industry or 'Electronics' in industry or 'Digital Mar' in industry or 'Data insights company' in industry or 'Digital Marketing' in industry:
        return 'Tech'
    elif 'Education' in industry or 'Currently studying . Previously worked in Power Generation' in industry or 'Not working at the moment, but previously I have been in the Education industry' in industry or 'i`m currently student' in industry or 'Student' in industry or 'I am a student' in industry or 'Unemployed, trying to switch career' in industry or 'Taking bootcamp' in industry or 'Interning in Sciences, Weather and Meteorological data' in industry:
        return 'Education'
    elif 'Construction' in industry or 'Manufacturing (Chemicals)' in industry or 'Manufa' in industry or 'Manufacturing' in industry or 'Manufacturering' in industry or 'General contractor' in industry or 'Cobsukting' in industry:
        return 'Construction'
    elif 'Aviation' in industry or 'Aerospace' in industry or 'Space & Defense' in industry:
        return 'Aviation'
    elif 'Insurance' in industry:
        return 'Insurance'
    elif 'Other (Please Specify)' in industry:
        return 'Other (Please Specify)'
    elif 'Utilities' in industry:
        return 'Utilities'
    elif 'Not working yet' in industry or 'None' in industry or 'None for now' in industry:
        return 'Not working yet'
    elif 'Manuf' in industry or 'Fashion/online store' in industry or 'sports' in industry or 'Agriculture' in industry or 'Management' in industry or 'Warehouse' in industry or 'NGO - Legislation' in industry or 'Cobsukting' in industry or 'Workforce' in industry:
        return 'Manuf'
    elif 'Consulting' in industry or 'Consulti' in industry or 'Cons' in industry or 'Consultation' in industry or 'Outsourcing' in industry or 'Cobsukting' in industry:
        return 'Consulting'
    elif 'Government' in industry or 'State Government' in industry or 'Culture' in industry or 'Government programs' in industry or 'Government Administration' in industry or 'State' in industry or 'Gover' in industry or 'Defense' in industry:
        return 'Government'
    elif 'Entertainment' in industry or 'sports' in industry or 'Social work' in industry or 'Hospitality' in industry:
        return 'Entertainment'
    elif 'Marketing' in industry or 'Advertising' in industry or 'Market research' in industry or 'Digital Marketing' in industry or 'Direct Marketing' in industry:
        return 'Marketing'
    elif 'Biotech' in industry:
        return 'Biotech'
    elif 'Semiconductor manufacturing' in industry:
        return 'Semiconductor manufacturing'
    elif 'Customer Service' in industry or 'Customer service' in industry:
        return 'Customer Service'
    elif 'Ecom' in industry or 'E-commerce' in industry or 'Ecommerce' in industry:
        return 'Ecom'
    elif 'Law Enforcement' in industry or 'Police / Emergency Services' in industry:
        return 'Law Enforcement'
    elif 'Not currently working' in industry or 'Home maker' in industry or 'Maritime' in industry or 'Urbanism' in industry or 'Looking for a job' in industry or 'Sensors' in industry or 'Professional Services' in industry or 'Home and living' in industry or 'Non Profit Organization' in industry or 'Homelessness' in industry:
        return 'Others/Not Specified'

In [19]:
# Apply the categorization function to create a new column 'Industry_Category'
df_copy['Industry_Category'] = df_copy["Working_Industry"].apply(categorize_industry)

In [20]:
df_copy["Industry_Category"].value_counts()

Tech                           154
Finance                         99
Healthcare                      84
Education                       46
Construction                    27
Telecommunication               22
Retail                          19
Logistics                       15
Manuf                           14
Consulting                      13
Marketing                       12
Government                      11
Clean Energy                    10
Others/Not Specified             9
Insurance                        6
Other (Please Specify)           5
Ecom                             5
Aviation                         4
Entertainment                    4
Utilities                        3
Not working yet                  3
Customer Service                 2
Law Enforcement                  2
Biotech                          1
Semiconductor manufacturing      1
Igaming                          1
Name: Industry_Category, dtype: int64

## <span style="color:green ">Favorite_Programming_Language</span>
### Python:
- Python

### R:
- R

### SQL:
- Other:SQL
- Other:Mostly use SQL but thatâ€™s not a programming language..
- Other:sql
- Other:If SQL is categorized as a programming language then I will definitely say SQL. Since I am still learning, I can't give a definite answer in relation to the above mentioned but for the sake of choosing I will say R then followed by Python
- Other:Sql
- Other:Knowledge of Excel and SQL yet
- Other:I don't use programming in my role
- Other:Excel/SQL
- Other:unknown
- Other:SQL Postgres
- Other:DAX
- Other:VBA
- Other:Stata
- Other:Excel
- Other:I currently do not work with programming languages yet
- Other:Altery
- Other:None
- Other:SQL
- Other:Just started learning
- Other:i mean, I mostly work in SQL and its variants?
- Other:SAS SQL
- Other:None at the moment
- Other:excel
- Other:I do analysis and create presentations based on datasets provided by others

### JavaScript:
- JavaScript

### C/C++:
- C/C++

### Unknown:
- Other:I donâ€™t know any
- Other:Dont require
- Other
- Other:unknown
- Other:NA
- Other:Mainly use Excel
- Other:SQL because that is all I know really well so far.
- Other:None at the moment

### Java:
- Java

### SAS:
- Other:SAS
- Other:SAS SQL

### MATLAB:
- Other:MATLAB

### PHP:
- Other:Php

In [21]:
# Define function to categorize programming languages
def categorize_language(language):
    if 'Python' in language:
        return 'Python'
    elif 'R' in language:
        return 'R'
    elif 'SQL' in language:
        return 'SQL'
    elif "Excel" in language:
        return "Excel"
    elif 'JavaScript' in language:
        return 'JavaScript'
    elif 'C/C++' in language:
        return 'C/C++'
    elif 'Java' in language:
        return 'Java'
    elif 'SAS' in language:
        return 'SAS'
    elif 'MATLAB' in language:
        return 'MATLAB'
    elif 'Php' in language:
        return 'PHP'
    else:
        return 'Unknown'

In [22]:
# Apply the categorization function to create a new column 'Language_Category'
df_copy['Favorite_Language_Category'] = df_copy['Favorite_Programming_Language'].apply(categorize_language)

In [23]:
df_copy["Favorite_Language_Category"].value_counts()

Python        420
R             102
Unknown        53
SQL            35
C/C++           7
JavaScript      6
Excel           2
SAS             2
Java            1
MATLAB          1
PHP             1
Name: Favorite_Language_Category, dtype: int64

## <span style="color:green">Happiness_Overall</span>
## Parameters for Question 6: "How Happy Are You in Your Current Position"

There are 6 parameters for Question 6, each representing a different aspect of satisfaction in the current position:

1. Salary
2. Work-Life Balance
3. Coworkers
4. Management
5. Upward Mobility
6. Learning New Things

To calculate an overall satisfaction score based on these parameters, follow these steps:

## Steps to Calculate Overall Satisfaction Score:

### Step 1: Calculate Average for Each Respondent

- For each respondent, calculate the average of their scores across all parameters.

```python
# Example Python Code
average_per_respondent = df[['Salary', 'Work-Life Balance', 'Coworkers', 'Management', 'Upward Mobility', 'Learning New Things']].mean(axis=1)

In [24]:
# create a new data frame for question 6
q6_df=df_copy[["Happiness_in_Pos(Salary)","Happiness_in_Pos(Work/Life Balance)","Happiness_in_Pos(Coworkers)",
         "Happiness_in_Pos(Management)","Happiness_in_Pos(Upward Mobility)","Happiness_in_Pos(Learning New Things)"]]

In [25]:
# take the average per respodent value and apply to the new column 
df_copy['Happiness_Overall'] = q6_df.apply(lambda row: round(row.mean()), axis=1)

## <span style="color:green">Preferred_Working_Condition</span>

In [26]:
# Define function to categorize job preferences
def categorize_job_preference(preference):
    if 'Remote' in preference:
        return 'Remote Work'
    elif 'Work/Life Balance' in preference:
        return 'Good Work/Life Balance'
    elif 'Salary' in preference:
        return 'Better Salary'
    elif 'Culture' in preference:
        return 'Good Culture'
    elif 'Responsibilities' in preference or 'Development' in preference:
        return 'Responsibilities and Development'
    elif 'Advancement' in preference:
        return 'Opportunity for Advancement'
    elif 'Learning' in preference or 'Skills' in preference:
        return 'Learning Opportunities'
    elif 'Passion' in preference or 'Data Analyst' in preference:
        return 'Passion for Data Analytics'
    elif 'Product Owner' in preference or 'Consulting' in preference:
        return 'Different Job Titles (Product Owner or Consulting)'
    elif 'Location' in preference or 'Country' in preference:
        return 'Desired Location (e.g., Australia to Canada)'
    elif 'All of the above' in preference:
        return 'All of the Above'
    else:
        return 'Other'

In [27]:
# Apply the categorization function to create a new column 'Job_Preference_Category'
df_copy['Job_Preference_Category'] = df_copy['Prefered_Working_Condition'].apply(categorize_job_preference)

In [28]:
df_copy["Job_Preference_Category"].value_counts()

Better Salary                       298
Remote Work                         128
Good Work/Life Balance              117
Good Culture                         55
Other                                24
Learning Opportunities                4
Responsibilities and Development      2
Passion for Data Analytics            1
All of the Above                      1
Name: Job_Preference_Category, dtype: int64

## <font color="blue">Current_Country</font>
### Standardizing country names

In [29]:
expand("Current_Country")

In [30]:
# Manual mapping of country names
country_mapping = {
    'United States': 'United States',
    'Canada': 'Canada',
    'Nigeria': 'Nigeria',
    'Republic democratic of Congo': 'Democratic Republic of the Congo',
    'Serbia': 'Serbia',
    'Argentina': 'Argentina',
    'United Kingdom': 'United Kingdom',
    'Niger': 'Niger',
    'Kenya': 'Kenya',
    'Azerbaijan': 'Azerbaijan',
    'Sudan': 'Sudan',
    'India': 'India',
    'Japan': 'Japan',
    'Greece': 'Greece',
    'PerÃº': 'Peru',
    'Australia': 'Australia',
    'Spain': 'Spain',
    'Barbados': 'Barbados',
    'South Africa': 'South Africa',
    'Colombia': 'Colombia',
    'Germany': 'Germany',
    'Bulgaria': 'Bulgaria',
    'Turkey': 'Turkey',
    'France': 'France',
    'Thailand': 'Thailand',
    'Netherlands': 'Netherlands',
    'Denmark': 'Denmark',
    'Brazil': 'Brazil',
    'Mexico': 'Mexico',
    'Chile': 'Chile',
    'Costa Rica': 'Costa Rica',
    'Vietnam': 'Vietnam',
    'Portugal': 'Portugal',
    'turkey': 'Turkey',
    'Egypt': 'Egypt',
    'Pakistan': 'Pakistan',
    'Ireland': 'Ireland',
    'Poland': 'Poland',
    'Mozambique': 'Mozambique',
    'Israel': 'Israel',
    'Singapore': 'Singapore',
    'Belgium': 'Belgium',
    'UAE': 'United Arab Emirates',
    'Somalia': 'Somalia',
    'Kosovo': 'Kosovo',
    'Iraq': 'Iraq',
    'Romania': 'Romania',
    'Peru': 'Peru',
    'Philippines': 'Philippines',
    'Malaysia': 'Malaysia',
    'nigeria': 'Nigeria',
    'Ghana': 'Ghana',
    'Portugsl': 'Portugal',
    'Macedonia': 'North Macedonia',
    'Irel': 'Ireland',
    'Morocco': 'Morocco',
    'Iran': 'Iran',
    'Bangladesh': 'Bangladesh',
    'Ire': 'Ireland',
    'Antigua': 'Antigua and Barbuda',
    'Venezuela': 'Venezuela',
    'Brazik': 'Brazil',
    'South Korea': 'South Korea',
    'Panama': 'Panama',
    'indonesia': 'Indonesia',
    'Angola': 'Angola',
    'Africa (Nigeria)': 'Nigeria',
    'Fin': 'Finland',
    'Austr': 'Australia',
    'Leba': 'Lebanon',
    'Saudi Arabia': 'Saudi Arabia',
    'United Arab Emirates': 'United Arab Emirates',
    'Zambia': 'Zambia',
    'ghana': 'Ghana',
    'Uruguay': 'Uruguay',
    'Indonesia': 'Indonesia',
    'Hong Kong': 'Hong Kong',
    'TUNISIA': 'Tunisia',
    'Sri lanka': 'Sri Lanka',
    'Kenua': 'Kenya',
    'Liberia': 'Liberia',
    'SG': 'Singapore',
    'Aisa': 'Asia',
    'Argentine': 'Argentina',
    'Sweden': 'Sweden',
    'Algeria': 'Algeria',
    'uzb': 'Uzbekistan',
    'Oman': 'Oman',
    'Other (Please Specify)':'Unknown'
}

In [31]:
# Apply the mapping to the 'Country' column
df_copy['Current_Country'] = df_copy['Current_Country'].map(country_mapping)

In [32]:
df_copy["Current_Country"].unique()

array(['United States', 'Canada', 'Nigeria',
       'Democratic Republic of the Congo', 'Unknown', 'Serbia',
       'Argentina', 'United Kingdom', 'Niger', 'Kenya', 'Azerbaijan',
       'Sudan', 'India', 'Japan', 'Greece', 'Peru', 'Australia', 'Spain',
       'Barbados', 'South Africa', 'Colombia', 'Germany', 'Bulgaria',
       'Turkey', 'France', 'Thailand', 'Netherlands', 'Denmark', 'Brazil',
       'Mexico', 'Chile', 'Costa Rica', 'Vietnam', 'Portugal', 'Egypt',
       'Pakistan', 'Ireland', 'Poland', 'Mozambique', 'Israel',
       'Singapore', 'Belgium', 'United Arab Emirates', 'Somalia',
       'Kosovo', 'Iraq', 'Romania', 'Philippines', 'Malaysia', 'Ghana',
       'North Macedonia', 'Morocco', 'Iran', 'Bangladesh',
       'Antigua and Barbuda', 'Venezuela', 'South Korea', 'Panama',
       'Indonesia', 'Angola', 'Finland', 'Lebanon', 'Saudi Arabia',
       'Zambia', 'Uruguay', 'Hong Kong', 'Tunisia', 'Sri Lanka',
       'Liberia', 'Asia', 'Sweden', 'Algeria', 'Uzbekistan', 'Oman'],
      dtype=object)

## <font color="green">Ethnicity</font>
### categorize into the following
- **White or Caucasian:**
  - White or Caucasian
  - Latino with Italian roots

- **Asian or Asian American:**
  - Asian or Asian American
  - South Asian
  - Indian
  - Bangladeshi
  - Pakistani
  - Russian
  - Melayu
  - Dravidian
  - Asian
  - South Indian

- **Black or African American:**
  - Black or African American
  - African
  - Kenyan African
  - Black African, Zimbabwean Citizen
  - Brown
  - Half Asian half African
  - Moroccan
  - Sudanese African
  - American Indian or Alaska Native

- **Hispanic or Latino:**
  - Hispanic or Latino
  - Latino with Italian roots

- **Other:**
  - Latino with Italian roots
  - Human
  - Race isn't a thing
  - Middleeas
  - Mixed (Caucasian / African-American)
  - Prefer not to ans
  - N/A
  - Other (Please Specify)
  - Kurdish
  - Native Hawaiian or other Pacific Islander
  - Egyp
  - Half black and half white
  - 7
  - Bla
  - Arab
  - Arabian (from Maghreb)
  - Greek
  - Nigeria
  - Bi-racial people should be able to check 2 options in 2022.
  - arab
  - Greek
  - Malayan

In [33]:
## expand the column
expand("Ethnicity")

In [34]:
# Mapping for categorization
ethnicity_mapping = {
    'White or Caucasian': 'White or Caucasian',
    'Asian or Asian American': 'Asian or Asian American',
    'Black or African American': 'Black or African American',
    'Hispanic or Latino': 'Hispanic or Latino',
    'Latino with Italian roots': 'Hispanic or Latino',
    'African': 'Black or African American',
    'South Asian': 'Asian or Asian American',
    'Indian': 'Asian or Asian American',
    'Kenyan African': 'Black or African American',
    'Black African, Zimbabwean Citizen': 'Black or African American',
    'Human': 'Other',
    "Race isn't a thing": 'Other',
    'Middleeas': 'Other',
    'Mixed ( Caucasian / African-American )': 'Other',
    'Half Asian half African': 'Other',
    'Brown': 'Black or African American',
    'Prefer not to ans': 'Other',
    'N/A': 'Other',
    'Other (Please Specify)': 'Other',
    'Kurdish': 'Other',
    'Native Hawaiian or other Pacific Islander': 'Other',
    'Bangladeshi': 'Asian or Asian American',
    'Pakistani': 'Asian or Asian American',
    'Russian': 'Asian or Asian American',
    'Egyp': 'Other',
    'Half black and half white': 'Other',
    '7': 'Other',
    'Bla': 'Black or African American',
    'Moroccan': 'Black or African American',
    'Arab': 'Other',
    'Sudanese African': 'Black or African American',
    'American Indian or Alaska Native': 'Black or African American',
    'Bi-racial people should be able to check 2 options in 2022.': 'Other',
    'Melayu': 'Asian or Asian American',
    'Dravidian': 'Asian or Asian American',
    'arab': 'Other',
    'Asian': 'Asian or Asian American',
    'South Indian': 'Asian or Asian American',
    'Greek': 'Other',
    'Nigeria': 'African',
    'Arabian (from Maghreb)': 'Other',
    'Malay': 'Asian or Asian American'
}

In [35]:
# Apply mapping to create the new column
df_copy['Ethnicity_Category'] = df_copy['Ethnicity'].map(ethnicity_mapping)

# seperate into two tables

In [36]:
## creating one table that contain info before processing
rawColumns=["Unique ID","Current_Role","Working_Industry","Favorite_Programming_Language","Happiness_in_Pos(Salary)",
           "Happiness_in_Pos(Work/Life Balance)","Happiness_in_Pos(Coworkers)","Happiness_in_Pos(Management)","Happiness_in_Pos(Upward Mobility)",
           "Happiness_in_Pos(Learning New Things)","Prefered_Working_Condition","Current_Country","Ethnicity"]
rawTable=df_copy[rawColumns]

In [37]:
## another table after categorizing features 
categorizedTable=pd.merge(df_copy["Unique ID"],df_copy.drop(columns=rawColumns),left_index=True,right_index=True)

# Save as Excel file

In [38]:

# Specify the Excel file path
excel_file_path = 'DataSurvey(Cleaned).xlsx'

# Create an ExcelWriter object
with pd.ExcelWriter(excel_file_path, engine='xlsxwriter') as writer:
    # Write each DataFrame to a different sheet
    rawTable.to_excel(writer, sheet_name='Sheet1', index=False)
    categorizedTable.to_excel(writer, sheet_name='Sheet2', index=False)